version: "3.3"

services:
  angular-app:
    image: yassineoooo/tp-frontend:latest
    ports:
      - "0.0.0.0:4200:80"

  spring-boot-app:
    image: yassineoooo/tp-backend:latest
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - demo:/var/lib/mysql

volumes:
  demo:
