name: CI Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot:latest ./springboot

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest ./angular-app

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest
