name: ci

on:
  push:
    branches: 
    - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code source
      uses: actions/checkout@v4

    - name: Build 
      run: |
        cd springboot/app
        chmod +x mvnw
        ./mvnw clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend springboot  
      run: |
        docker build -t spring-app springboot/app

    - name: Build front-end angular  
      run: |
        docker build -t angular-app angular-app/

    - name: test avec dockr compose   
      run: |
        docker compose down 
        docker compose up -d 